/**
 * Local AsyncStorage service for packing list management
 * Fallback when Firebase is not configured
 */

import AsyncStorage from "@react-native-async-storage/async-storage";
import { PackingItem, CampingStyle } from "../types/camping";

const PACKING_STORAGE_KEY = "packing_lists";

interface StoredPackingLists {
  [tripId: string]: PackingItem[];
}

/**
 * Get packing lists from storage
 */
async function getStoredLists(): Promise<StoredPackingLists> {
  try {
    const data = await AsyncStorage.getItem(PACKING_STORAGE_KEY);
    return data ? JSON.parse(data) : {};
  } catch (error) {
    console.error("Error reading packing lists from storage:", error);
    return {};
  }
}

/**
 * Save packing lists to storage
 */
async function saveStoredLists(lists: StoredPackingLists): Promise<void> {
  try {
    await AsyncStorage.setItem(PACKING_STORAGE_KEY, JSON.stringify(lists));
  } catch (error) {
    console.error("Error saving packing lists to storage:", error);
  }
}

/**
 * Get all packing items for a trip
 */
export async function getPackingList(tripId: string): Promise<PackingItem[]> {
  const lists = await getStoredLists();
  return lists[tripId] || [];
}

/**
 * Add a packing item
 */
export async function addPackingItem(
  tripId: string,
  item: Omit<PackingItem, "id">
): Promise<string> {
  const lists = await getStoredLists();
  const tripItems = lists[tripId] || [];

  const newId = `item_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  const newItem: PackingItem = {
    ...item,
    id: newId,
  };

  lists[tripId] = [...tripItems, newItem];
  await saveStoredLists(lists);

  return newId;
}

/**
 * Update a packing item
 */
export async function updatePackingItem(
  tripId: string,
  itemId: string,
  updates: Partial<PackingItem>
): Promise<void> {
  const lists = await getStoredLists();
  const tripItems = lists[tripId] || [];

  const updatedItems = tripItems.map((item) =>
    item.id === itemId ? { ...item, ...updates } : item
  );

  lists[tripId] = updatedItems;
  await saveStoredLists(lists);
}

/**
 * Toggle packed status
 */
export async function togglePackingItem(
  tripId: string,
  itemId: string,
  isPacked: boolean
): Promise<void> {
  return updatePackingItem(tripId, itemId, { isPacked });
}

/**
 * Delete a packing item
 */
export async function deletePackingItem(
  tripId: string,
  itemId: string
): Promise<void> {
  const lists = await getStoredLists();
  const tripItems = lists[tripId] || [];

  lists[tripId] = tripItems.filter((item) => item.id !== itemId);
  await saveStoredLists(lists);
}

/**
 * Template items for different camping styles
 */
const PACKING_TEMPLATES: Record<
  CampingStyle,
  Array<Omit<PackingItem, "id" | "isPacked">>
> = {
  CAR_CAMPING: [
    { category: "Shelter", label: "Tent", quantity: 1, isAutoGenerated: true },
    { category: "Shelter", label: "Stakes and guylines", quantity: 1, isAutoGenerated: true },
    { category: "Shelter", label: "Footprint or tarp", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Sleeping bag", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Sleeping pad", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Pillow", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Camp stove", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Fuel", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Lighter or matches", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Cookware", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Utensils", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Cooler", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Water bottles", quantity: 2, isAutoGenerated: true },
    { category: "Clothing", label: "Rain jacket", quantity: 1, isAutoGenerated: true },
    { category: "Clothing", label: "Extra layers", quantity: 2, isAutoGenerated: true },
    { category: "Clothing", label: "Extra socks", quantity: 3, isAutoGenerated: true },
    { category: "Tools", label: "Headlamp", quantity: 1, isAutoGenerated: true },
    { category: "Tools", label: "Multi-tool", quantity: 1, isAutoGenerated: true },
    { category: "Tools", label: "Camp chairs", quantity: 2, isAutoGenerated: true },
    { category: "Tools", label: "Lantern", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "First aid kit", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "Emergency whistle", quantity: 1, isAutoGenerated: true },
    { category: "Personal items", label: "Sunscreen", quantity: 1, isAutoGenerated: true },
    { category: "Personal items", label: "Bug spray", quantity: 1, isAutoGenerated: true },
    { category: "Personal items", label: "Toiletries", quantity: 1, isAutoGenerated: true },
  ],
  BACKPACKING: [
    { category: "Shelter", label: "Backpacking tent", quantity: 1, isAutoGenerated: true },
    { category: "Shelter", label: "Stakes and guylines", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Sleeping bag", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Sleeping pad", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Backpacking stove", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Fuel canister", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Pot/cup combo", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Spork", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Water filter", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Water bottles", quantity: 2, isAutoGenerated: true },
    { category: "Clothing", label: "Base layers", quantity: 2, isAutoGenerated: true },
    { category: "Clothing", label: "Rain jacket", quantity: 1, isAutoGenerated: true },
    { category: "Clothing", label: "Extra socks", quantity: 3, isAutoGenerated: true },
    { category: "Tools", label: "Backpack", quantity: 1, isAutoGenerated: true },
    { category: "Tools", label: "Trekking poles", quantity: 1, isAutoGenerated: true },
    { category: "Tools", label: "Headlamp", quantity: 1, isAutoGenerated: true },
    { category: "Tools", label: "Multi-tool", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "First aid kit", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "Map and compass", quantity: 1, isAutoGenerated: true },
    { category: "Personal items", label: "Sunscreen", quantity: 1, isAutoGenerated: true },
    { category: "Personal items", label: "Bug spray", quantity: 1, isAutoGenerated: true },
  ],
  RV: [
    { category: "RV setup", label: "Leveling blocks", quantity: 1, isAutoGenerated: true },
    { category: "RV setup", label: "Wheel chocks", quantity: 1, isAutoGenerated: true },
    { category: "RV setup", label: "Power adapter", quantity: 1, isAutoGenerated: true },
    { category: "RV setup", label: "Water hose", quantity: 1, isAutoGenerated: true },
    { category: "RV setup", label: "Sewer hose", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Cookware", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Utensils", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Cooler", quantity: 1, isAutoGenerated: true },
    { category: "Tools", label: "Camp chairs", quantity: 2, isAutoGenerated: true },
    { category: "Tools", label: "Outdoor rug", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "First aid kit", quantity: 1, isAutoGenerated: true },
    { category: "Personal items", label: "Toiletries", quantity: 1, isAutoGenerated: true },
  ],
  HAMMOCK: [
    { category: "Shelter", label: "Hammock", quantity: 1, isAutoGenerated: true },
    { category: "Shelter", label: "Suspension straps", quantity: 1, isAutoGenerated: true },
    { category: "Shelter", label: "Rain tarp", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Underquilt", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Top quilt/sleeping bag", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Camp stove", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Fuel", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Cookware", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Water filter", quantity: 1, isAutoGenerated: true },
    { category: "Clothing", label: "Base layers", quantity: 2, isAutoGenerated: true },
    { category: "Clothing", label: "Rain jacket", quantity: 1, isAutoGenerated: true },
    { category: "Tools", label: "Headlamp", quantity: 1, isAutoGenerated: true },
    { category: "Tools", label: "Multi-tool", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "First aid kit", quantity: 1, isAutoGenerated: true },
  ],
  ROOFTOP_TENT: [
    { category: "Shelter", label: "Rooftop tent", quantity: 1, isAutoGenerated: true },
    { category: "Shelter", label: "Ladder", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Sleeping bag", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Pillow", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Camp stove", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Cooler", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Cookware", quantity: 1, isAutoGenerated: true },
    { category: "Tools", label: "Camp chairs", quantity: 2, isAutoGenerated: true },
    { category: "Tools", label: "Awning", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "First aid kit", quantity: 1, isAutoGenerated: true },
  ],
  OVERLANDING: [
    { category: "Vehicle", label: "Recovery gear", quantity: 1, isAutoGenerated: true },
    { category: "Vehicle", label: "Spare tire", quantity: 1, isAutoGenerated: true },
    { category: "Vehicle", label: "Tool kit", quantity: 1, isAutoGenerated: true },
    { category: "Vehicle", label: "Air compressor", quantity: 1, isAutoGenerated: true },
    { category: "Shelter", label: "Tent or awning", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Sleeping bag", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Camp stove", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Cooler", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Water storage", quantity: 1, isAutoGenerated: true },
    { category: "Navigation", label: "GPS device", quantity: 1, isAutoGenerated: true },
    { category: "Navigation", label: "Maps", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "First aid kit", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "Emergency communication", quantity: 1, isAutoGenerated: true },
  ],
  BOAT_CANOE: [
    { category: "Watercraft", label: "Boat/canoe", quantity: 1, isAutoGenerated: true },
    { category: "Watercraft", label: "Paddles", quantity: 2, isAutoGenerated: true },
    { category: "Watercraft", label: "Life jackets", quantity: 2, isAutoGenerated: true },
    { category: "Watercraft", label: "Dry bags", quantity: 3, isAutoGenerated: true },
    { category: "Shelter", label: "Tent", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Sleeping bag", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Waterproof stove", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Water filter", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "First aid kit", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "Emergency whistle", quantity: 1, isAutoGenerated: true },
  ],
  BIKEPACKING: [
    { category: "Bike gear", label: "Bike bags", quantity: 1, isAutoGenerated: true },
    { category: "Bike gear", label: "Repair kit", quantity: 1, isAutoGenerated: true },
    { category: "Bike gear", label: "Spare tubes", quantity: 2, isAutoGenerated: true },
    { category: "Bike gear", label: "Pump", quantity: 1, isAutoGenerated: true },
    { category: "Shelter", label: "Lightweight tent", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Sleeping bag", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Sleeping pad", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Compact stove", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Water bottles", quantity: 3, isAutoGenerated: true },
    { category: "Safety and first aid", label: "First aid kit", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "Bike helmet", quantity: 1, isAutoGenerated: true },
  ],
  WINTER: [
    { category: "Shelter", label: "4-season tent", quantity: 1, isAutoGenerated: true },
    { category: "Shelter", label: "Snow stakes", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Winter sleeping bag", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Insulated sleeping pad", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Liquid fuel stove", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Insulated water bottles", quantity: 2, isAutoGenerated: true },
    { category: "Clothing", label: "Insulated jacket", quantity: 1, isAutoGenerated: true },
    { category: "Clothing", label: "Snow pants", quantity: 1, isAutoGenerated: true },
    { category: "Clothing", label: "Winter boots", quantity: 1, isAutoGenerated: true },
    { category: "Clothing", label: "Gloves", quantity: 2, isAutoGenerated: true },
    { category: "Clothing", label: "Warm hat", quantity: 1, isAutoGenerated: true },
    { category: "Tools", label: "Snow shovel", quantity: 1, isAutoGenerated: true },
    { category: "Tools", label: "Hand warmers", quantity: 5, isAutoGenerated: true },
    { category: "Safety and first aid", label: "First aid kit", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "Avalanche gear", quantity: 1, isAutoGenerated: true },
  ],
  DISPERSED: [
    { category: "Shelter", label: "Tent", quantity: 1, isAutoGenerated: true },
    { category: "Shelter", label: "Stakes and guylines", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Sleeping bag", quantity: 1, isAutoGenerated: true },
    { category: "Sleep system", label: "Sleeping pad", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Camp stove", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Water filter", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Water storage", quantity: 1, isAutoGenerated: true },
    { category: "Kitchen", label: "Trash bags", quantity: 3, isAutoGenerated: true },
    { category: "Navigation", label: "GPS or maps", quantity: 1, isAutoGenerated: true },
    { category: "Navigation", label: "Compass", quantity: 1, isAutoGenerated: true },
    { category: "Tools", label: "Shovel", quantity: 1, isAutoGenerated: true },
    { category: "Tools", label: "Headlamp", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "First aid kit", quantity: 1, isAutoGenerated: true },
    { category: "Safety and first aid", label: "Emergency whistle", quantity: 1, isAutoGenerated: true },
  ],
};

/**
 * Generate packing list from template
 */
export async function generatePackingListFromTemplate(
  tripId: string,
  campStyle: CampingStyle
): Promise<void> {
  const template = PACKING_TEMPLATES[campStyle] || PACKING_TEMPLATES.CAR_CAMPING;
  const lists = await getStoredLists();

  // Create items with IDs
  const items: PackingItem[] = template.map((item) => ({
    ...item,
    id: `item_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    isPacked: false,
  }));

  lists[tripId] = items;
  await saveStoredLists(lists);
}
