import {
  collection,
  doc,
  addDoc,
  getDoc,
  getDocs,
  updateDoc,
  deleteDoc,
  query,
  where,
  orderBy,
  onSnapshot,
  writeBatch,
} from "firebase/firestore";
import { db } from "../config/firebase";
import type { PackingItem, DEFAULT_PACKING_CATEGORIES } from "../types/packing";
import type { Trip } from "../types/camping";

const USERS_COLLECTION = "users";

/**
 * Get packing list collection reference for a trip
 */
function getPackingListCollection(userId: string, tripId: string) {
  return collection(db, USERS_COLLECTION, userId, "trips", tripId, "packingList");
}

/**
 * Add a packing item
 */
export async function addPackingItem(
  userId: string,
  tripId: string,
  itemData: Omit<PackingItem, "id" | "createdAt" | "updatedAt">
): Promise<string> {
  const packingRef = getPackingListCollection(userId, tripId);
  const now = new Date().toISOString();

  const newItem = {
    ...itemData,
    createdAt: now,
    updatedAt: now,
  };

  const docRef = await addDoc(packingRef, newItem);
  return docRef.id;
}

/**
 * Get all packing items for a trip
 */
export async function getPackingList(userId: string, tripId: string): Promise<PackingItem[]> {
  const packingRef = getPackingListCollection(userId, tripId);
  const q = query(packingRef, orderBy("category"), orderBy("label"));
  const snapshot = await getDocs(q);

  return snapshot.docs.map((doc) => ({
    id: doc.id,
    ...doc.data(),
  })) as PackingItem[];
}

/**
 * Update a packing item
 */
export async function updatePackingItem(
  userId: string,
  tripId: string,
  itemId: string,
  updates: Partial<PackingItem>
): Promise<void> {
  const itemRef = doc(db, USERS_COLLECTION, userId, "trips", tripId, "packingList", itemId);
  await updateDoc(itemRef, {
    ...updates,
    updatedAt: new Date().toISOString(),
  });
}

/**
 * Toggle packed status of an item
 */
export async function togglePackedStatus(
  userId: string,
  tripId: string,
  itemId: string,
  isPacked: boolean
): Promise<void> {
  await updatePackingItem(userId, tripId, itemId, { isPacked });
}

/**
 * Delete a packing item
 */
export async function deletePackingItem(
  userId: string,
  tripId: string,
  itemId: string
): Promise<void> {
  const itemRef = doc(db, USERS_COLLECTION, userId, "trips", tripId, "packingList", itemId);
  await deleteDoc(itemRef);
}

/**
 * Delete all items in a category
 */
export async function deletePackingCategory(
  userId: string,
  tripId: string,
  category: string
): Promise<void> {
  const packingRef = getPackingListCollection(userId, tripId);
  const q = query(packingRef, where("category", "==", category));
  const snapshot = await getDocs(q);

  const batch = writeBatch(db);
  snapshot.docs.forEach((doc) => {
    batch.delete(doc.ref);
  });
  await batch.commit();
}

/**
 * Auto-generate packing list based on trip details
 */
export async function generatePackingList(
  userId: string,
  tripId: string,
  trip: Trip
): Promise<void> {
  const batch = writeBatch(db);
  const packingRef = getPackingListCollection(userId, tripId);

  // Get existing auto-generated items
  const existing = await getPackingList(userId, tripId);
  const autoGenerated = existing.filter((item) => item.isAutoGenerated);

  // Delete existing auto-generated items
  autoGenerated.forEach((item) => {
    const itemRef = doc(db, USERS_COLLECTION, userId, "trips", tripId, "packingList", item.id);
    batch.delete(itemRef);
  });

  // Generate base items based on camping style
  const baseItems = getBasePackingItems(trip.campingStyle);

  // Add weather/season specific items
  const seasonItems = getSeasonSpecificItems(trip);

  const allItems = [...baseItems, ...seasonItems];

  // Add new items
  allItems.forEach((item) => {
    const docRef = doc(collection(db, USERS_COLLECTION, userId, "trips", tripId, "packingList"));
    batch.set(docRef, {
      ...item,
      isAutoGenerated: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });
  });

  await batch.commit();
}

/**
 * Get base packing items for camping style
 */
function getBasePackingItems(
  campingStyle?: string
): Omit<PackingItem, "id" | "createdAt" | "updatedAt" | "isAutoGenerated">[] {
  // Base items for all camping
  const baseItems = [
    { category: "Shelter", label: "Tent", quantity: 1, isPacked: false, notes: "" },
    { category: "Shelter", label: "Stakes and guylines", quantity: 1, isPacked: false, notes: "" },
    { category: "Shelter", label: "Footprint or tarp", quantity: 1, isPacked: false, notes: "" },
    { category: "Sleep system", label: "Sleeping bag", quantity: 1, isPacked: false, notes: "" },
    { category: "Sleep system", label: "Sleeping pad", quantity: 1, isPacked: false, notes: "" },
    { category: "Sleep system", label: "Pillow", quantity: 1, isPacked: false, notes: "" },
    { category: "Kitchen", label: "Camp stove", quantity: 1, isPacked: false, notes: "" },
    { category: "Kitchen", label: "Fuel", quantity: 1, isPacked: false, notes: "" },
    { category: "Kitchen", label: "Lighter or matches", quantity: 1, isPacked: false, notes: "" },
    { category: "Kitchen", label: "Cookware", quantity: 1, isPacked: false, notes: "" },
    { category: "Kitchen", label: "Utensils", quantity: 1, isPacked: false, notes: "" },
    { category: "Kitchen", label: "Plates and bowls", quantity: 1, isPacked: false, notes: "" },
    { category: "Kitchen", label: "Water bottles", quantity: 2, isPacked: false, notes: "" },
    { category: "Clothing", label: "Base layers", quantity: 2, isPacked: false, notes: "" },
    { category: "Clothing", label: "Insulation layer", quantity: 1, isPacked: false, notes: "" },
    { category: "Clothing", label: "Rain jacket", quantity: 1, isPacked: false, notes: "" },
    { category: "Clothing", label: "Hiking boots", quantity: 1, isPacked: false, notes: "" },
    { category: "Clothing", label: "Extra socks", quantity: 3, isPacked: false, notes: "" },
    { category: "Tools", label: "Headlamp", quantity: 1, isPacked: false, notes: "" },
    { category: "Tools", label: "Multi-tool or knife", quantity: 1, isPacked: false, notes: "" },
    { category: "Tools", label: "Duct tape", quantity: 1, isPacked: false, notes: "" },
    { category: "Safety and first aid", label: "First aid kit", quantity: 1, isPacked: false, notes: "" },
    { category: "Safety and first aid", label: "Emergency whistle", quantity: 1, isPacked: false, notes: "" },
    { category: "Safety and first aid", label: "Map and compass", quantity: 1, isPacked: false, notes: "" },
    { category: "Personal items", label: "Sunscreen", quantity: 1, isPacked: false, notes: "" },
    { category: "Personal items", label: "Bug spray", quantity: 1, isPacked: false, notes: "" },
    { category: "Personal items", label: "Toiletries", quantity: 1, isPacked: false, notes: "" },
    { category: "Personal items", label: "Towel", quantity: 1, isPacked: false, notes: "" },
  ];

  // Add style-specific items
  if (campingStyle === "BACKPACKING") {
    baseItems.push(
      { category: "Tools", label: "Backpack", quantity: 1, isPacked: false, notes: "" },
      { category: "Tools", label: "Trekking poles", quantity: 1, isPacked: false, notes: "" },
      { category: "Kitchen", label: "Water filter", quantity: 1, isPacked: false, notes: "" }
    );
  } else if (campingStyle === "CAR_CAMPING") {
    baseItems.push(
      { category: "Camp comfort", label: "Camp chairs", quantity: 2, isPacked: false, notes: "" },
      { category: "Camp comfort", label: "Cooler", quantity: 1, isPacked: false, notes: "" },
      { category: "Camp comfort", label: "Lantern", quantity: 1, isPacked: false, notes: "" }
    );
  } else if (campingStyle === "WINTER") {
    baseItems.push(
      { category: "Sleep system", label: "4-season sleeping bag", quantity: 1, isPacked: false, notes: "" },
      { category: "Sleep system", label: "Insulated sleeping pad", quantity: 1, isPacked: false, notes: "" }
    );
  }

  return baseItems;
}

/**
 * Get season-specific items based on trip dates and forecast
 */
function getSeasonSpecificItems(
  trip: Trip
): Omit<PackingItem, "id" | "createdAt" | "updatedAt" | "isAutoGenerated">[] {
  const items: Omit<PackingItem, "id" | "createdAt" | "updatedAt" | "isAutoGenerated">[] = [];
  const startDate = new Date(trip.startDate);
  const month = startDate.getMonth();

  // Cold weather (Nov-Mar)
  if (month >= 10 || month <= 2) {
    items.push(
      { category: "Season specific items", label: "Insulated gloves", quantity: 1, isPacked: false, notes: "" },
      { category: "Season specific items", label: "Warm hat", quantity: 1, isPacked: false, notes: "" },
      { category: "Season specific items", label: "Thermal base layers", quantity: 2, isPacked: false, notes: "" },
      { category: "Season specific items", label: "Insulated jacket", quantity: 1, isPacked: false, notes: "" }
    );
  }

  // Hot weather (Jun-Aug)
  if (month >= 5 && month <= 7) {
    items.push(
      { category: "Season specific items", label: "Sun hat", quantity: 1, isPacked: false, notes: "" },
      { category: "Season specific items", label: "Sunglasses", quantity: 1, isPacked: false, notes: "" },
      { category: "Season specific items", label: "Electrolyte powder", quantity: 1, isPacked: false, notes: "" },
      { category: "Season specific items", label: "Shade tarp", quantity: 1, isPacked: false, notes: "" }
    );
  }

  return items;
}

/**
 * Subscribe to real-time packing list updates
 */
export function subscribeToPackingList(
  userId: string,
  tripId: string,
  callback: (items: PackingItem[]) => void
): () => void {
  const packingRef = getPackingListCollection(userId, tripId);
  const q = query(packingRef, orderBy("category"), orderBy("label"));

  return onSnapshot(q, (snapshot) => {
    const items = snapshot.docs.map((doc) => ({
      id: doc.id,
      ...doc.data(),
    })) as PackingItem[];
    callback(items);
  });
}
