// Packing list types for Firebase-based data model

export interface PackingItem {
  id: string;
  category: string;
  label: string;
  quantity: number;
  isPacked: boolean;
  isAutoGenerated: boolean;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface PackingCategory {
  id: string;
  name: string;
  items: PackingItem[];
}

// Default packing categories
export const DEFAULT_PACKING_CATEGORIES = [
  "Shelter",
  "Sleep system",
  "Kitchen",
  "Clothing",
  "Tools",
  "Safety and first aid",
  "Personal items",
  "Trip specific items",
  "Season specific items",
  "Food and kitchen",
] as const;

export type DefaultPackingCategory = typeof DEFAULT_PACKING_CATEGORIES[number];
