/**
 * Mock data for camping templates and meal library
 * In production, this would be seeded into Firebase
 */

import { CampTemplate, MealLibraryItem, PackingItem } from "../types/camping";

// Base categories that apply to all camping types
const BASE_CATEGORIES = {
  SHELTER: "Shelter",
  SLEEP: "Sleep System",
  KITCHEN: "Kitchen",
  CLOTHING: "Clothing",
  TOOLS: "Tools",
  SAFETY: "Safety and First Aid",
  PERSONAL: "Personal Items",
  TRIP_SPECIFIC: "Trip Specific",
};

// Car Camping Template
export const CAR_CAMPING_TEMPLATE: CampTemplate = {
  id: "CAR_CAMPING",
  campStyle: "CAR_CAMPING",
  name: "Car Camping Essentials",
  baseItems: [
    // Shelter
    { category: BASE_CATEGORIES.SHELTER, label: "Tent", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.SHELTER, label: "Tent stakes", quantity: 8, isAutoGenerated: true },
    { category: BASE_CATEGORIES.SHELTER, label: "Rain fly", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.SHELTER, label: "Ground tarp", quantity: 1, isAutoGenerated: true },

    // Sleep System
    { category: BASE_CATEGORIES.SLEEP, label: "Sleeping bag", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.SLEEP, label: "Sleeping pad", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.SLEEP, label: "Pillow", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.SLEEP, label: "Camp chair", quantity: 1, isAutoGenerated: true },

    // Kitchen
    { category: BASE_CATEGORIES.KITCHEN, label: "Camp stove", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.KITCHEN, label: "Fuel", quantity: 2, isAutoGenerated: true },
    { category: BASE_CATEGORIES.KITCHEN, label: "Cookware set", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.KITCHEN, label: "Utensils", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.KITCHEN, label: "Plates/bowls", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.KITCHEN, label: "Cooler", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.KITCHEN, label: "Water bottles", quantity: 2, isAutoGenerated: true },
    { category: BASE_CATEGORIES.KITCHEN, label: "Water filter", quantity: 1, isAutoGenerated: true },

    // Tools
    { category: BASE_CATEGORIES.TOOLS, label: "Headlamp", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.TOOLS, label: "Flashlight", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.TOOLS, label: "Multi-tool", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.TOOLS, label: "Rope", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.TOOLS, label: "Duct tape", quantity: 1, isAutoGenerated: true },

    // Safety and First Aid
    { category: BASE_CATEGORIES.SAFETY, label: "First aid kit", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.SAFETY, label: "Whistle", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.SAFETY, label: "Emergency blanket", quantity: 1, isAutoGenerated: true },

    // Personal
    { category: BASE_CATEGORIES.PERSONAL, label: "Sunscreen", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.PERSONAL, label: "Bug spray", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.PERSONAL, label: "Toiletries", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.PERSONAL, label: "Toilet paper", quantity: 1, isAutoGenerated: true },
  ],
  seasonalModifiers: {
    cold: [
      { category: BASE_CATEGORIES.CLOTHING, label: "Warm sleeping bag", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.CLOTHING, label: "Insulated pad", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.CLOTHING, label: "Thermal layers", quantity: 2, isAutoGenerated: true },
      { category: BASE_CATEGORIES.CLOTHING, label: "Gloves", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.CLOTHING, label: "Beanie", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.KITCHEN, label: "Hot water bottle", quantity: 1, isAutoGenerated: true },
    ],
    rainy: [
      { category: BASE_CATEGORIES.CLOTHING, label: "Rain jacket", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.CLOTHING, label: "Rain pants", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.CLOTHING, label: "Extra socks", quantity: 3, isAutoGenerated: true },
      { category: BASE_CATEGORIES.SHELTER, label: "Extra tarp", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.TOOLS, label: "Waterproof bags", quantity: 3, isAutoGenerated: true },
    ],
    hot: [
      { category: BASE_CATEGORIES.CLOTHING, label: "Sun hat", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.PERSONAL, label: "Extra sunscreen", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.SHELTER, label: "Shade tarp", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.KITCHEN, label: "Electrolyte powder", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.PERSONAL, label: "Cooling towel", quantity: 1, isAutoGenerated: true },
    ],
  },
};

// Backpacking Template
export const BACKPACKING_TEMPLATE: CampTemplate = {
  id: "BACKPACKING",
  campStyle: "BACKPACKING",
  name: "Backpacking Essentials",
  baseItems: [
    // Shelter
    { category: BASE_CATEGORIES.SHELTER, label: "Backpacking tent", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.SHELTER, label: "Tent stakes", quantity: 6, isAutoGenerated: true },

    // Sleep System
    { category: BASE_CATEGORIES.SLEEP, label: "Ultralight sleeping bag", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.SLEEP, label: "Sleeping pad", quantity: 1, isAutoGenerated: true },

    // Kitchen
    { category: BASE_CATEGORIES.KITCHEN, label: "Backpacking stove", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.KITCHEN, label: "Fuel canister", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.KITCHEN, label: "Pot", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.KITCHEN, label: "Spork", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.KITCHEN, label: "Water filter", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.KITCHEN, label: "Water bottles", quantity: 2, isAutoGenerated: true },

    // Tools
    { category: BASE_CATEGORIES.TOOLS, label: "Headlamp", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.TOOLS, label: "Multi-tool", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.TOOLS, label: "Map and compass", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.TOOLS, label: "Trekking poles", quantity: 2, isAutoGenerated: true },

    // Safety
    { category: BASE_CATEGORIES.SAFETY, label: "First aid kit", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.SAFETY, label: "Emergency shelter", quantity: 1, isAutoGenerated: true },

    // Personal
    { category: BASE_CATEGORIES.PERSONAL, label: "Sunscreen", quantity: 1, isAutoGenerated: true },
    { category: BASE_CATEGORIES.PERSONAL, label: "Bug spray", quantity: 1, isAutoGenerated: true },
  ],
  seasonalModifiers: {
    cold: [
      { category: BASE_CATEGORIES.CLOTHING, label: "4-season sleeping bag", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.CLOTHING, label: "Insulated jacket", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.CLOTHING, label: "Thermal layers", quantity: 2, isAutoGenerated: true },
      { category: BASE_CATEGORIES.CLOTHING, label: "Gloves", quantity: 1, isAutoGenerated: true },
    ],
    rainy: [
      { category: BASE_CATEGORIES.CLOTHING, label: "Rain jacket", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.CLOTHING, label: "Rain pants", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.TOOLS, label: "Waterproof bags", quantity: 2, isAutoGenerated: true },
    ],
    hot: [
      { category: BASE_CATEGORIES.CLOTHING, label: "Sun hat", quantity: 1, isAutoGenerated: true },
      { category: BASE_CATEGORIES.KITCHEN, label: "Electrolyte tablets", quantity: 1, isAutoGenerated: true },
    ],
  },
};

// All templates
export const CAMP_TEMPLATES: Record<string, CampTemplate> = {
  CAR_CAMPING: CAR_CAMPING_TEMPLATE,
  BACKPACKING: BACKPACKING_TEMPLATE,
  // Add more templates as needed
};

// Meal Library
export const MEAL_LIBRARY: MealLibraryItem[] = [
  // Breakfast
  {
    id: "meal_oatmeal",
    name: "Instant Oatmeal",
    category: "breakfast",
    prepType: "campStove",
    difficulty: "easy",
    ingredients: ["Instant oatmeal packets", "Water", "Dried fruit", "Nuts"],
    instructions: "Boil water, pour over oatmeal, let sit 2 minutes. Add toppings.",
    tags: ["quick", "vegetarian"],
  },
  {
    id: "meal_breakfast_burrito",
    name: "Breakfast Burritos",
    category: "breakfast",
    prepType: "campStove",
    difficulty: "moderate",
    ingredients: ["Eggs", "Tortillas", "Cheese", "Sausage", "Bell peppers"],
    instructions: "Scramble eggs with veggies and meat. Wrap in tortilla with cheese.",
    tags: ["hearty", "protein"],
  },
  {
    id: "meal_granola",
    name: "Granola and Yogurt",
    category: "breakfast",
    prepType: "noCook",
    difficulty: "easy",
    ingredients: ["Granola", "Greek yogurt", "Fresh berries"],
    instructions: "Layer yogurt with granola and berries. Keep yogurt in cooler.",
    tags: ["quick", "no-cook", "vegetarian"],
  },

  // Lunch
  {
    id: "meal_sandwich",
    name: "Trail Sandwiches",
    category: "lunch",
    prepType: "noCook",
    difficulty: "easy",
    ingredients: ["Bread", "Deli meat", "Cheese", "Lettuce", "Condiments"],
    instructions: "Assemble sandwiches. Keep meat and cheese in cooler.",
    tags: ["no-cook", "quick"],
  },
  {
    id: "meal_wraps",
    name: "Chicken Caesar Wraps",
    category: "lunch",
    prepType: "noCook",
    difficulty: "easy",
    ingredients: ["Tortillas", "Grilled chicken", "Romaine", "Caesar dressing", "Parmesan"],
    instructions: "Wrap chicken, lettuce, and dressing in tortilla. Add cheese.",
    tags: ["no-cook", "protein"],
  },
  {
    id: "meal_ramen",
    name: "Upgraded Ramen",
    category: "lunch",
    prepType: "campStove",
    difficulty: "easy",
    ingredients: ["Ramen noodles", "Egg", "Green onions", "Soy sauce"],
    instructions: "Cook ramen, add beaten egg in last minute. Top with onions.",
    tags: ["hot", "quick"],
  },

  // Dinner
  {
    id: "meal_chili",
    name: "One-Pot Chili",
    category: "dinner",
    prepType: "campStove",
    difficulty: "moderate",
    ingredients: ["Ground beef", "Beans", "Tomatoes", "Chili spices", "Onions"],
    instructions: "Brown beef, add veggies and beans. Simmer 20 min.",
    tags: ["hearty", "warm"],
  },
  {
    id: "meal_pasta",
    name: "Camping Pasta",
    category: "dinner",
    prepType: "campStove",
    difficulty: "easy",
    ingredients: ["Pasta", "Jar sauce", "Ground meat", "Parmesan"],
    instructions: "Cook pasta, brown meat, mix with sauce. Top with cheese.",
    tags: ["easy", "filling"],
  },
  {
    id: "meal_tacos",
    name: "Camp Tacos",
    category: "dinner",
    prepType: "campStove",
    difficulty: "moderate",
    ingredients: ["Tortillas", "Ground beef", "Taco seasoning", "Toppings", "Cheese"],
    instructions: "Cook seasoned meat. Assemble tacos with toppings.",
    tags: ["crowd-pleaser", "customizable"],
  },
  {
    id: "meal_foil_packets",
    name: "Foil Packet Dinners",
    category: "dinner",
    prepType: "campfire",
    difficulty: "easy",
    ingredients: ["Chicken or fish", "Vegetables", "Butter", "Seasonings", "Foil"],
    instructions: "Wrap protein and veggies in foil. Cook on coals 15-20 min.",
    tags: ["campfire", "easy-cleanup"],
  },

  // Snacks
  {
    id: "meal_trail_mix",
    name: "Trail Mix",
    category: "snack",
    prepType: "noCook",
    difficulty: "easy",
    ingredients: ["Mixed nuts", "Dried fruit", "Chocolate chips", "Granola"],
    instructions: "Mix ingredients. Store in ziplock bags.",
    tags: ["no-cook", "energy"],
  },
  {
    id: "meal_smores",
    name: "S'mores",
    category: "snack",
    prepType: "campfire",
    difficulty: "easy",
    ingredients: ["Graham crackers", "Marshmallows", "Chocolate bars"],
    instructions: "Toast marshmallow over fire. Sandwich with chocolate between crackers.",
    tags: ["campfire", "dessert", "classic"],
  },
  {
    id: "meal_fruit",
    name: "Fresh Fruit",
    category: "snack",
    prepType: "noCook",
    difficulty: "easy",
    ingredients: ["Apples", "Oranges", "Bananas", "Grapes"],
    instructions: "Wash and enjoy. Choose durable fruits that travel well.",
    tags: ["no-cook", "healthy"],
  },
];
